### ISSUE TITLE
Mention the source of the data directly in the application

### ISSUE THREAD

**Issue by Bartozzz** [Bartozzz/foodie-app#2]
E.g. images, links to OFF etc.

**Comment by teolemon** [comment]
swell :-)
Are you on the Open Food Facts slack ? Also binaries ready to install would be cool :)

**Comment by Bartozzz** [comment]
Closed by 66d6b54.

<img width="796" src="https://user-images.githubusercontent.com/6741707/45712695-452a8f00-bb8d-11e8-8d2b-7cf6b09489b6.png">

---

@teolemon I'll upload some releases once this app will be completed. And yep, I am on OFF Slack, but most of the time I am just lurking my job channels, so I may miss a few things on Open Food Facts. 😄
